name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git operations
    
    - name: Debug git configuration
      run: |
        echo "Git version: $(git --version)"
        echo "Current directory: $(pwd)"
        echo "Git status: $(git status --porcelain || echo 'Git status failed')"
        echo "Git remote: $(git remote -v || echo 'No remotes')"
        echo "Git branch: $(git branch -a || echo 'No branches')"
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run tests
      run: cargo test --verbose
      
    - name: Check formatting
      run: cargo fmt -- --check
      
    - name: Run clippy
      run: cargo clippy -- -D warnings

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git operations
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Build
      run: cargo build --release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: patingin-${{ matrix.os }}
        path: target/release/patingin*
        compression-level: 6